menu:
  Index:
    url: /
    External: false
    name: 首页
  Tags:
    url: /tags/
    External: false
    name: 标签
#  Categories:
#    url: /categories/
#    External: false
#    name: 分类
  Archives:
    url: /archives/
    External: false
    name: 归档
  About:
    url: /about/
    External: false
    name: 关于

dark_theme:
  enable: true

# 联系方式
contact:
  github: "https://github.com/f-dong"
  twitter:
  weibo:
  zhihu:
  facebook:

# 是否显示封面图片
showFeatureImage: true

# 首页头像图片
avatar: /images/avatar.png

# 谷歌统计 跟踪 ID
ga: ""

# 百度统计 The baidu web analytics
baidu_tongji: "1634f217ef6dcf0fbd06b3ad984296b1"

comment:
  enable: false
  system: twikoo # 可选 gitalk、twikoo
  config:
    gitalk:
      clientId:
      clientSecret:
      repository: # 仓库名
      owner: # 仓库所有者
      createIssueManually: false # 如果当前页面没有相应的 isssue 且登录的用户属于 admin，则会自动创建 issue。如果设置为 true，则显示一个初始化页面，创建 issue 需要点击 init 按钮。
    twikoo:
      envId: "https://twikoo.codeover.cn" #  腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
      region: # 环境地域，腾讯云传
      mark: "blog" # 一个twikoo服务端应用于多个内容时，可填写此项

# 底部链接
bottom_link:
  icp:
    url: https://beian.miit.gov.cn
    text: 豫ICP备2022011962号
    class: icp
  gongan:
    url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=41010402002848
    text: 豫公网安备41010402002848号
    class: icp
  rss:
    url: # beian.miit.gov.cn
    text: # 沪ICP备 09007032号-1
    class: icp

# 底部显示来源信息
bottom_source:
  enable: true

# 脚注
footnote:
  enable: true # 是否开启脚注解析
  ignoreCodeBlock: true # 是否忽略代码块中的脚注

# 图片配置
image:
  lazyload_enable: true # 图片懒加载
  photo_zoom: simple-lightbox # 可选 simple-lightbox、fancybox、false(禁用)

# cdn 配置
cdn:
  enable: false
  # CDN 提供者
  provider: jsdelivr # 可选 jsdelivr、unpkg、bootcdn
